// flow-typed signature: b9be2b31fe59c5056cc2318c41a05148
// flow-typed version: <<STUB>>/html2pdf.js_v0.9.1/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html2pdf.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html2pdf.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html2pdf.js/dist/html2pdf' {
  declare module.exports: any;
}

declare module 'html2pdf.js/dist/include/html2pdf.es' {
  declare module.exports: any;
}

declare module 'html2pdf.js/dist/require/html2pdf.cjs' {
  declare module.exports: any;
}

declare module 'html2pdf.js/gulpfile' {
  declare module.exports: any;
}

declare module 'html2pdf.js/rollup.config' {
  declare module.exports: any;
}

declare module 'html2pdf.js/src/index' {
  declare module.exports: any;
}

declare module 'html2pdf.js/src/plugin/hyperlinks' {
  declare module.exports: any;
}

declare module 'html2pdf.js/src/plugin/jspdf-plugin' {
  declare module.exports: any;
}

declare module 'html2pdf.js/src/plugin/pagebreaks' {
  declare module.exports: any;
}

declare module 'html2pdf.js/src/utils' {
  declare module.exports: any;
}

declare module 'html2pdf.js/src/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html2pdf.js/dist/html2pdf.js' {
  declare module.exports: $Exports<'html2pdf.js/dist/html2pdf'>;
}
declare module 'html2pdf.js/dist/include/html2pdf.es.js' {
  declare module.exports: $Exports<'html2pdf.js/dist/include/html2pdf.es'>;
}
declare module 'html2pdf.js/dist/require/html2pdf.cjs.js' {
  declare module.exports: $Exports<'html2pdf.js/dist/require/html2pdf.cjs'>;
}
declare module 'html2pdf.js/gulpfile.js' {
  declare module.exports: $Exports<'html2pdf.js/gulpfile'>;
}
declare module 'html2pdf.js/rollup.config.js' {
  declare module.exports: $Exports<'html2pdf.js/rollup.config'>;
}
declare module 'html2pdf.js/src/index.js' {
  declare module.exports: $Exports<'html2pdf.js/src/index'>;
}
declare module 'html2pdf.js/src/plugin/hyperlinks.js' {
  declare module.exports: $Exports<'html2pdf.js/src/plugin/hyperlinks'>;
}
declare module 'html2pdf.js/src/plugin/jspdf-plugin.js' {
  declare module.exports: $Exports<'html2pdf.js/src/plugin/jspdf-plugin'>;
}
declare module 'html2pdf.js/src/plugin/pagebreaks.js' {
  declare module.exports: $Exports<'html2pdf.js/src/plugin/pagebreaks'>;
}
declare module 'html2pdf.js/src/utils.js' {
  declare module.exports: $Exports<'html2pdf.js/src/utils'>;
}
declare module 'html2pdf.js/src/worker.js' {
  declare module.exports: $Exports<'html2pdf.js/src/worker'>;
}
