// flow-typed signature: 5914deb58a18e2154b591366c668f5ce
// flow-typed version: <<STUB>>/pdfmake_v^0.1.36/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pdfmake'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pdfmake' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pdfmake/build/pdfmake' {
  declare module.exports: any;
}

declare module 'pdfmake/build/pdfmake.min' {
  declare module.exports: any;
}

declare module 'pdfmake/build/vfs_fonts' {
  declare module.exports: any;
}

declare module 'pdfmake/gulpfile' {
  declare module.exports: any;
}

declare module 'pdfmake/src/browser-extensions/pdfMake' {
  declare module.exports: any;
}

declare module 'pdfmake/src/browser-extensions/virtual-fs' {
  declare module.exports: any;
}

declare module 'pdfmake/src/columnCalculator' {
  declare module.exports: any;
}

declare module 'pdfmake/src/docMeasure' {
  declare module.exports: any;
}

declare module 'pdfmake/src/docPreprocessor' {
  declare module.exports: any;
}

declare module 'pdfmake/src/documentContext' {
  declare module.exports: any;
}

declare module 'pdfmake/src/elementWriter' {
  declare module.exports: any;
}

declare module 'pdfmake/src/fontProvider' {
  declare module.exports: any;
}

declare module 'pdfmake/src/helpers' {
  declare module.exports: any;
}

declare module 'pdfmake/src/imageMeasure' {
  declare module.exports: any;
}

declare module 'pdfmake/src/layoutBuilder' {
  declare module.exports: any;
}

declare module 'pdfmake/src/line' {
  declare module.exports: any;
}

declare module 'pdfmake/src/pageElementWriter' {
  declare module.exports: any;
}

declare module 'pdfmake/src/printer' {
  declare module.exports: any;
}

declare module 'pdfmake/src/qrEnc' {
  declare module.exports: any;
}

declare module 'pdfmake/src/standardPageSizes' {
  declare module.exports: any;
}

declare module 'pdfmake/src/styleContextStack' {
  declare module.exports: any;
}

declare module 'pdfmake/src/tableProcessor' {
  declare module.exports: any;
}

declare module 'pdfmake/src/textDecorator' {
  declare module.exports: any;
}

declare module 'pdfmake/src/textTools' {
  declare module.exports: any;
}

declare module 'pdfmake/src/traversalTracker' {
  declare module.exports: any;
}

declare module 'pdfmake/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pdfmake/build/pdfmake.js' {
  declare module.exports: $Exports<'pdfmake/build/pdfmake'>;
}
declare module 'pdfmake/build/pdfmake.min.js' {
  declare module.exports: $Exports<'pdfmake/build/pdfmake.min'>;
}
declare module 'pdfmake/build/vfs_fonts.js' {
  declare module.exports: $Exports<'pdfmake/build/vfs_fonts'>;
}
declare module 'pdfmake/gulpfile.js' {
  declare module.exports: $Exports<'pdfmake/gulpfile'>;
}
declare module 'pdfmake/src/browser-extensions/pdfMake.js' {
  declare module.exports: $Exports<'pdfmake/src/browser-extensions/pdfMake'>;
}
declare module 'pdfmake/src/browser-extensions/virtual-fs.js' {
  declare module.exports: $Exports<'pdfmake/src/browser-extensions/virtual-fs'>;
}
declare module 'pdfmake/src/columnCalculator.js' {
  declare module.exports: $Exports<'pdfmake/src/columnCalculator'>;
}
declare module 'pdfmake/src/docMeasure.js' {
  declare module.exports: $Exports<'pdfmake/src/docMeasure'>;
}
declare module 'pdfmake/src/docPreprocessor.js' {
  declare module.exports: $Exports<'pdfmake/src/docPreprocessor'>;
}
declare module 'pdfmake/src/documentContext.js' {
  declare module.exports: $Exports<'pdfmake/src/documentContext'>;
}
declare module 'pdfmake/src/elementWriter.js' {
  declare module.exports: $Exports<'pdfmake/src/elementWriter'>;
}
declare module 'pdfmake/src/fontProvider.js' {
  declare module.exports: $Exports<'pdfmake/src/fontProvider'>;
}
declare module 'pdfmake/src/helpers.js' {
  declare module.exports: $Exports<'pdfmake/src/helpers'>;
}
declare module 'pdfmake/src/imageMeasure.js' {
  declare module.exports: $Exports<'pdfmake/src/imageMeasure'>;
}
declare module 'pdfmake/src/layoutBuilder.js' {
  declare module.exports: $Exports<'pdfmake/src/layoutBuilder'>;
}
declare module 'pdfmake/src/line.js' {
  declare module.exports: $Exports<'pdfmake/src/line'>;
}
declare module 'pdfmake/src/pageElementWriter.js' {
  declare module.exports: $Exports<'pdfmake/src/pageElementWriter'>;
}
declare module 'pdfmake/src/printer.js' {
  declare module.exports: $Exports<'pdfmake/src/printer'>;
}
declare module 'pdfmake/src/qrEnc.js' {
  declare module.exports: $Exports<'pdfmake/src/qrEnc'>;
}
declare module 'pdfmake/src/standardPageSizes.js' {
  declare module.exports: $Exports<'pdfmake/src/standardPageSizes'>;
}
declare module 'pdfmake/src/styleContextStack.js' {
  declare module.exports: $Exports<'pdfmake/src/styleContextStack'>;
}
declare module 'pdfmake/src/tableProcessor.js' {
  declare module.exports: $Exports<'pdfmake/src/tableProcessor'>;
}
declare module 'pdfmake/src/textDecorator.js' {
  declare module.exports: $Exports<'pdfmake/src/textDecorator'>;
}
declare module 'pdfmake/src/textTools.js' {
  declare module.exports: $Exports<'pdfmake/src/textTools'>;
}
declare module 'pdfmake/src/traversalTracker.js' {
  declare module.exports: $Exports<'pdfmake/src/traversalTracker'>;
}
declare module 'pdfmake/webpack.config.js' {
  declare module.exports: $Exports<'pdfmake/webpack.config'>;
}
