const FAQ_PATH = `${process.env.PUBLIC_URL}/faq`;
const FORM_PATH = `${process.env.PUBLIC_URL}/form`;
const HOME_PATH = `${process.env.PUBLIC_URL}/`;

const PARENTAL_STATUS_LIVING = 'living';
const PARENTAL_STATUS_DECEASED = 'deceased';
const PARENTAL_STATUS_LEGAL_CUSTODY_SIGNED = 'legal-custody-signed';
const PARENTAL_STATUS_LEGAL_CUSTODY_SENT = 'legal-custody-sent';
const PARENTAL_STATUS_LEGAL_CUSTODY_NO_CONSENT = 'legal-custody-no-consent';

export {
  FAQ_PATH,
  FORM_PATH,
  HOME_PATH,
  PARENTAL_STATUS_LIVING,
  PARENTAL_STATUS_DECEASED,
  PARENTAL_STATUS_LEGAL_CUSTODY_SIGNED,
  PARENTAL_STATUS_LEGAL_CUSTODY_SENT,
  PARENTAL_STATUS_LEGAL_CUSTODY_NO_CONSENT
};
